// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Courses_and_Lections.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208084711_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("capacity");

                    b.Property<int>("CourseLeader")
                        .HasColumnType("int")
                        .HasColumnName("courseLeader");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("courseName");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("startDate");

                    b.HasKey("CourseID");

                    b.ToTable("courseTable");
                });

            modelBuilder.Entity("Lecture", b =>
                {
                    b.Property<int>("LectureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lectureID");

                    b.Property<int>("CourseID")
                        .HasColumnType("int")
                        .HasColumnName("courseID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime>("LectureDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dateTimeOfLecture");

                    b.Property<string>("LectureName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lectureName");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("LectureID");

                    b.ToTable("lectureTable");
                });
#pragma warning restore 612, 618
        }
    }
}
