<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Course_and_Lection.WebAPI</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Course-and-Lection.Application\Course-and-Lection.Application.csproj" />
      <ProjectReference Include="..\Course-and-Lection.Infrastructure\Course-and-Lection.Infrastructure.csproj" />
      <ProjectReference Include="..\Course-and-Lection.Persistance\Course-and-Lection.Persistance.csproj" />
    </ItemGroup>

</Project>
