<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <RootNamespace>Course_and_Lection.Persistance</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Course-and-Lection.Application\Course-and-Lection.Application.csproj" />
      <ProjectReference Include="..\Course-and-Lection.Core\Course-and-Lection.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
    </ItemGroup>

</Project>
